@startuml
[*] --> Выключено
Выключено --> В_процессе_работы : Включение
В_процессе_работы --> Выключено : Ручное выключение
В_процессе_работы --> Завершено : Таймер истек
Завершено --> Выключено : Автоматический переход при обновлении
@enduml